version: "2.1"
services:
  db:
    image: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbTP
      MYSQL_ROOT_PASSWORD: tp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
      container_name: nodejs
      build: ./
      ports:
        - "3000:3000"
      volumes:
        - .:/app
      environment:
        MYSQL_HOST_IP: db
      restart: always

volumes:
  mysql_data:
    driver: local

